Repository chulgang/hrd, pull requests merged in 2024-08, with the labels that each got.

#110 [#109] 남은 자리 조회 기능 추가
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
Labels: enhancement

#112 [#111] 남은 자리 수정 기능 추가
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
Labels: enhancement

#113 [#106] 시간대 조회 기능 추가
  src/main/java/org/chulgang/hrd/classroom/exception/ExceptionMessage.java
  src/main/java/org/chulgang/hrd/classroom/exception/TimePeriodIdNotFoundException.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepository.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepositoryImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/ClassroomServiceImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodService.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodServiceImpl.java
Labels: enhancement

#115 [#114] 시간대 조회 기능 변경
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepository.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepositoryImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodService.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodServiceImpl.java
Labels: enhancement

#116 [#107] 강의실 이름 조회 기능 추가
  src/main/java/org/chulgang/hrd/classroom/exception/ClassroomNotFoundException.java
  src/main/java/org/chulgang/hrd/classroom/exception/ExceptionMessage.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/ClassroomRepository.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/ClassroomRepositoryImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/ClassroomService.java
  src/main/java/org/chulgang/hrd/classroom/model/service/ClassroomServiceImpl.java
Labels: enhancement

#118 [#108] 객체의 반환 파라미터와 포워딩 경로 변경에 따른 테스트 코드 업데이트
  src/test/java/org/chulgang/hrd/course/controller/RegisterCourseControllerTest.java
Labels: test

#120 [#119] 결제 서비스에 제공되는 강좌 정보 반환 메서드 추가
  src/main/java/org/chulgang/hrd/course/dto/CourseResponseForPayment.java
  src/main/java/org/chulgang/hrd/course/dto/GetCourseResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/SubjectRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CoursePaymentService.java
  src/main/java/org/chulgang/hrd/course/model/service/CoursePaymentServiceImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/SubjectService.java
  src/main/java/org/chulgang/hrd/course/model/service/SubjectServiceImpl.java
  src/test/java/org/chulgang/hrd/course/controller/GetCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestObjectFactory.java
Labels: enhancement

#123 [#121] 강좌 도메인에 인증 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/webapp/elearn/login-failed.jsp
Labels: enhancement, view

#125 [#119] CourseResponseForPayment 클래스에 Getter 추가
  src/main/java/org/chulgang/hrd/course/dto/CourseResponseForPayment.java
Labels: enhancement

#126 [#72] SQL문 DDL 수정
  src/main/resources/schema.sql
Labels: enhancement

#128 [#72] SQL문 DDL 수정
  src/main/resources/schema.sql
Labels: enhancement

#131 feat(post): 게시글 권한별, header, footer 추가
  src/main/java/org/chulgang/hrd/post/controller/DeletePostController.java
  src/main/java/org/chulgang/hrd/post/controller/InsertPostController.java
  src/main/java/org/chulgang/hrd/post/controller/UpdatePostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/ContentFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/InsertFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/ListFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/PostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/UpdateFormPostController.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/webapp/elearn/post.jsp
  src/main/webapp/elearn/postContent.jsp
  src/main/webapp/elearn/postInput.jsp
  src/main/webapp/elearn/postList.jsp
  src/main/webapp/elearn/postUpdate.jsp
Labels: enhancement

#132 fix(post): 게시글 Controller 위치 변경
  src/main/java/org/chulgang/hrd/post/controller/ContentFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/InsertFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/UpdateFormPostController.java
Labels: bug, enhancement

#133 fix(post): 게시글 header 수정
  src/main/java/org/chulgang/hrd/post/controller/PostController.java
  src/main/webapp/elearn/header.jsp
  src/main/webapp/elearn/postList.jsp
Labels: bug, enhancement

#139 [#121] 강좌 등록 시 강좌 테이블에 강사 ID 저장 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/dto/CreateCourseRequest.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
Labels: enhancement

#140 [#72] SQL문 DDL 수정
  src/main/resources/schema.sql
Labels: enhancement

#143 [#121] 로그인 사용자가 강사가 아닐 시 강좌 등록 버튼을 숨김 처리하는 기능 추가
  src/main/webapp/elearn/course-registration-form.jsp
Labels: enhancement, view

#145 [#124] 테스트 코드에 TimePeriodService 관련 변수 추가
  src/test/java/org/chulgang/hrd/course/controller/RegisterCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
Labels: test

#149 [#121] 강사 회원이 아닐 시 강좌를 등록할 수 없도록 하는 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
Labels: enhancement

#151 [#150] 강좌 등록 시 사용된 시간대가 반영되지 않는 문제 해결
  src/main/java/org/chulgang/hrd/classroom/dto/UpdateUsedTimePeriodRequest.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepositoryImpl.java
  src/main/webapp/elearn/course-registration-form.jsp
Labels: bug

#159 [#158] 과목명 조회 시 ResultSet을 받아 오지 못하는 문제 해결
  src/main/java/org/chulgang/hrd/course/model/repository/SubjectRepositoryImpl.java
Labels: bug

#162 [#161] 강의실 이름 조회 시 ResultSet을 받아 오지 못하는 문제 해결
  src/main/java/org/chulgang/hrd/classroom/model/repository/ClassroomRepositoryImpl.java
Labels: bug

#164 [#163] 강좌 목록 조회 페이지 추가
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/java/org/chulgang/hrd/course/dto/CreateCourseRequest.java
  src/main/java/org/chulgang/hrd/course/dto/GetCourseResponse.java
  src/main/java/org/chulgang/hrd/course/dto/GetCoursesResponse.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/webapp/elearn/courses-grid.jsp
Labels: enhancement, view

#167 [#163] 테스트 코드에 프로덕션 코드 수정 반영
  src/test/java/org/chulgang/hrd/course/controller/GetCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/controller/GetCoursesControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
Labels: test

#168 [#163] 서비스 컴포넌트의 변경사항 반영
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/model/service/CoursePaymentServiceImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
Labels: enhancement

#169 [#163] 컨트롤러 컴포넌트의 변경사항 반영
  src/main/java/org/chulgang/hrd/course/controller/GetCourseController.java
Labels: enhancement

#172 [#171] 강좌 결제 데이터 전송 오류 해결
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/dto/GetCourseResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
Labels: bug

#173 [#156] 강좌 상세 조회 기능 구현
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/webapp/elearn/authorization-failed.jsp
  src/main/webapp/elearn/course-details.jsp
Labels: enhancement, view

#174 [#157] 강좌 남은 자리 소진 시 신청 종료 기능 추가
  src/main/webapp/elearn/course-details.jsp
Labels: enhancement, view

#176 [#175] 남은 자리 조회 시 ResultSet을 받아 오지 못하는 문제 해결
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
Labels: bug

#178 [#177] 헤더 수정, 강좌 도메인 헤더 적용
  src/main/webapp/elearn/course-details.jsp
  src/main/webapp/elearn/course-registration-form.jsp
  src/main/webapp/elearn/courses-grid.jsp
  src/main/webapp/elearn/header.jsp
Labels: view

#181 [#180] SQL문 DDL과 예시 데이터 변경
  src/main/resources/insert.sql
  src/main/resources/schema.sql
Labels: enhancement

#183 [#182] 강좌 목록 페이지 수정
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/webapp/elearn/course-details.jsp
  src/main/webapp/elearn/course-registration-form.jsp
  src/main/webapp/elearn/courses-grid.jsp
Labels: view

#185 feat(post): 게시판 전반적인 수정
  src/main/java/org/chulgang/hrd/post/controller/form/ContentFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/ListFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/PostController.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepository.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/java/org/chulgang/hrd/post/model/service/PostService.java
  src/main/java/org/chulgang/hrd/post/model/service/PostServiceImpl.java
  src/main/java/org/chulgang/hrd/post/model/sql/PostSQL.java
  src/main/webapp/elearn/post.jsp
  src/main/webapp/elearn/postContent.jsp
Labels: enhancement

#187 [#182, #186] 강좌 목록 페이지에서 페이지 번호가 표시되지 않는 문제 해결
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CoursePaymentServiceImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/resources/schema.sql
  src/main/webapp/elearn/courses-grid.jsp
Labels: bug

#193 [#191] 새로운 강좌 저장이 되지 않는 문제 수정
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
Labels: bug

#194 feat(all): 전반적인 jsp 수정
  src/main/java/org/chulgang/hrd/post/controller/form/ContentFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/form/PostController.java
  src/main/webapp/elearn/charge.jsp
  src/main/webapp/elearn/course-details.jsp
  src/main/webapp/elearn/course-registration-form.jsp
  src/main/webapp/elearn/courses-grid.jsp
  src/main/webapp/elearn/footer.jsp
  src/main/webapp/elearn/header.jsp
  src/main/webapp/elearn/index.jsp
  src/main/webapp/elearn/myPage.jsp
  src/main/webapp/elearn/paid-course-list.jsp
  src/main/webapp/elearn/post.jsp
  src/main/webapp/elearn/postContent.jsp
  src/main/webapp/elearn/postInput.jsp
  src/main/webapp/elearn/postList.jsp
  src/main/webapp/elearn/postUpdate.jsp
  src/main/webapp/elearn/reservation-detail.jsp
  src/main/webapp/elearn/reservation-list.jsp
Labels: enhancement

#198 [#197] docs: README.md 파일 업데이트
  README.md
  src/main/resources/insert.sql
Labels: documentation

#199 [#197] README.md 파일 업데이트
  README.md
Labels: documentation

#200 [#197] README.md 파일 업데이트
  README.md
Labels: documentation

#204 [#197] README.md 파일 업데이트
  README.md
Labels: documentation

#206 [#205] 프로덕션 코드 변경사항에 맞춰 테스트 코드 변경
  src/main/java/org/chulgang/hrd/course/controller/GetCourseController.java
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/dto/GetCourseResponse.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/test/java/org/chulgang/hrd/course/controller/GetCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/controller/GetCoursesControllerTest.java
  src/test/java/org/chulgang/hrd/course/controller/RegisterCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestConstant.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestObjectFactory.java
  src/test/java/org/chulgang/hrd/util/DatabaseUtilTest.java
Labels: test
