Repository chulgang/hrd, pull requests merged in 2024-07, with the labels that each got.

#3 [#2] README.md 추가
  README.md
Labels: documentation

#5 [#4] 전체 프로젝트의 로깅 프로세스 추가
  pom.xml
  src/main/java/org/chulgang/hrd/aop/LoggingAspect.java
  src/main/java/org/chulgang/hrd/filtration/LoggingFilter.java
  src/main/java/org/chulgang/hrd/util/LogConstant.java
  src/main/java/org/chulgang/hrd/util/PerformanceMeasurer.java
Labels: enhancement, configuration

#7 [#6] 로깅 AOP에서 작업 수행 메서드의 파라미터명을 받아 오지 못하는 문제 해결
  pom.xml
Labels: bug

#9 [#8] 로깅 필터 적용 후 톰캣 서버 배포가 실패하는 문제 해결
  src/main/webapp/WEB-INF/web.xml
Labels: bug

#11 [#10] 리플렉션 추가 후 기존 view가 로드되지 않는 문제 해결
  pom.xml
Labels: bug

#13 [#12] EL, JSTL 의존성 추가
  pom.xml
Labels: configuration

#14 [#12] glassfish 의존성 추가
  pom.xml
Labels: configuration

#19 [#18] Repository 테스트를 위한 H2 데이터베이스 설정 추가
  src/main/java/org/chulgang/hrd/util/ConfigConstant.java
  src/main/java/org/chulgang/hrd/util/DbConnection.java
Labels: configuration

#22 [#20] 공통 예외 처리를 위한 GlobalExceptionHandler 클래스 추가
  src/main/java/org/chulgang/hrd/exception/GlobalExceptionHandler.java
Labels: enhancement

#25 [#24] 형 변환 시 일부 예외 메시지의 형식이 맞지 않는 문제 해결
  src/main/java/org/chulgang/hrd/util/FormatConverter.java
Labels: bug

#28 [#15] 강좌 목록 조회 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/dto/GetCoursesResponse.java
  src/main/java/org/chulgang/hrd/course/exception/CourseIdNotFoundException.java
  src/main/java/org/chulgang/hrd/course/exception/ExceptionMessage.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/java/org/chulgang/hrd/util/AppContextListener.java
  src/main/java/org/chulgang/hrd/util/ConnectionContainer.java
  src/main/java/org/chulgang/hrd/util/DataSelector.java
  src/main/java/org/chulgang/hrd/util/FormatValidator.java
  src/main/java/org/chulgang/hrd/util/StatementGenerator.java
  src/test/java/org/chulgang/hrd/course/controller/GetCoursesControllerTest.java
  src/test/java/org/chulgang/hrd/course/domain/CourseTest.java
  src/test/java/org/chulgang/hrd/course/model/repository/CourseRepositoryTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestConstant.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestDataProvider.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestObjectFactory.java
Labels: enhancement, test

#31 [#29] 강좌 조회 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/GetCourseController.java
  src/main/java/org/chulgang/hrd/course/dto/GetCourseResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/exception/ArgumentNoValueException.java
  src/main/java/org/chulgang/hrd/exception/ClosingResultSetFailedException.java
  src/main/java/org/chulgang/hrd/exception/ClosingStatementFailedException.java
  src/main/java/org/chulgang/hrd/exception/EntityNotFoundException.java
  src/test/java/org/chulgang/hrd/course/controller/GetCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/repository/CourseRepositoryTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
Labels: enhancement, test

#33 [#32] 예외 메시지 상수 추가
  src/main/java/org/chulgang/hrd/exception/ExceptionMessage.java
Labels: enhancement

#35 [#34] 강좌 등록 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/dto/CreateCourseRequest.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/test/java/org/chulgang/hrd/course/controller/RegisterCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/repository/CourseRepositoryTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
Labels: enhancement, test

#36 [#34] 강좌 엔티티의 팩토리 메서드 추가
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
Labels: enhancement

#38 [#37] 데이터베이스에서 강좌 목록 조회 시 예외가 발생하는 문제 수정
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
Labels: bug

#45 feat(post): 게시글 등록 기능 추가
  src/main/java/org/chulgang/hrd/post/controller/InsertFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/InsertPostController.java
  src/main/java/org/chulgang/hrd/post/controller/PostController.java
  src/main/java/org/chulgang/hrd/post/domain/Post.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepository.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/java/org/chulgang/hrd/post/model/service/PostService.java
  src/main/java/org/chulgang/hrd/post/model/service/PostServiceImpl.java
  src/main/webapp/elearn/post.jsp
  src/main/webapp/elearn/postInput.jsp
Labels: bug, enhancement

#46 [#44] 전체 페이지 수 계산 기능 추가
  src/main/java/org/chulgang/hrd/course/dto/GetCoursesResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/test/java/org/chulgang/hrd/course/controller/GetCoursesControllerTest.java
  src/test/java/org/chulgang/hrd/course/domain/CourseTest.java
  src/test/java/org/chulgang/hrd/course/model/repository/CourseRepositoryTest.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestConstant.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestDataProvider.java
Labels: enhancement, test

#47 Feature/post/sql post
  src/main/java/org/chulgang/hrd/post/model/sql/PostSQL.java
Labels: enhancement

#49 feat(post): 게시글 중복 선택 버그 해결
  src/main/java/org/chulgang/hrd/post/domain/Post.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/webapp/elearn/post.jsp
Labels: bug

#62 [#61] 강좌명 중복 여부 확인 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/GetCoursesController.java
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/test/java/org/chulgang/hrd/course/controller/GetCoursesControllerTest.java
  src/test/java/org/chulgang/hrd/course/controller/RegisterCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/repository/CourseRepositoryTest.java
  src/test/java/org/chulgang/hrd/course/model/service/CourseServiceTest.java
Labels: enhancement, test

#63 feat(post): 게시판 작성 VIEW 구현
  src/main/java/org/chulgang/hrd/post/domain/Post.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/webapp/elearn/postInput.jsp
Labels: enhancement

#66 [#65] 과목 목록 조회 기능 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Subject.java
  src/main/java/org/chulgang/hrd/course/dto/GetSubjectResponse.java
  src/main/java/org/chulgang/hrd/course/dto/GetSubjectsResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/SubjectRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/SubjectRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/SubjectService.java
  src/main/java/org/chulgang/hrd/course/model/service/SubjectServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/java/org/chulgang/hrd/util/AppContextListener.java
Labels: enhancement

#69 [#68] 강의실 목록 조회 기능 추가
  src/main/java/org/chulgang/hrd/classroom/domain/Classroom.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetClassroomResponse.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetClassroomsResponse.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/ClassroomRepository.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/ClassroomRepositoryImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/ClassroomService.java
  src/main/java/org/chulgang/hrd/classroom/model/service/ClassroomServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/java/org/chulgang/hrd/util/AppContextListener.java
Labels: enhancement

#71 [#68] 강의실 목록 인스턴스의 서블릿 포워딩 추가
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
Labels: enhancement

#73 [#72] SQL문 DDL 수정
  src/main/resources/schema.sql
Labels: enhancement

#84 [#74] 강의실 예약 가능 시간대 목록 조회 기능 추가
  src/main/java/org/chulgang/hrd/classroom/controller/GetTimePeriodsController.java
  src/main/java/org/chulgang/hrd/classroom/domain/Period.java
  src/main/java/org/chulgang/hrd/classroom/domain/TimePeriod.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetClassroomResponse.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetTimePeriodResponse.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetTimePeriodsResponse.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepository.java
  src/main/java/org/chulgang/hrd/classroom/model/repository/TimePeriodRepositoryImpl.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodService.java
  src/main/java/org/chulgang/hrd/classroom/model/service/TimePeriodServiceImpl.java
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/java/org/chulgang/hrd/exception/ExceptionMessage.java
  src/main/java/org/chulgang/hrd/exception/JsonSerializationFailedException.java
  src/main/java/org/chulgang/hrd/util/AppContextListener.java
  src/main/java/org/chulgang/hrd/util/FormatConverter.java
Labels: enhancement

#86 feat(post): content 권한별 관리
  src/main/java/org/chulgang/hrd/post/controller/ContentFormPostController.java
  src/main/java/org/chulgang/hrd/post/controller/PostController.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/webapp/elearn/post.jsp
  src/main/webapp/elearn/postContent.jsp
Labels: enhancement

#87 feat(post) : 게시판 삭제 구현
  src/main/java/org/chulgang/hrd/post/controller/DeletePostController.java
  src/main/java/org/chulgang/hrd/post/controller/UpdateFormPostController.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepository.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/java/org/chulgang/hrd/post/model/service/PostService.java
  src/main/java/org/chulgang/hrd/post/model/service/PostServiceImpl.java
  src/main/java/org/chulgang/hrd/post/model/sql/PostSQL.java
Labels: enhancement

#89 [#88] 연속 요청 시 데이터베이스 연결이 끊어지는 문제 해결
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/java/org/chulgang/hrd/util/AppContextListener.java
  src/main/java/org/chulgang/hrd/util/DatabaseUtil.java
Labels: bug

#92 feat(post): 수정 게시판
  src/main/java/org/chulgang/hrd/post/controller/UpdatePostController.java
  src/main/webapp/elearn/postUpdate.jsp
Labels: enhancement

#95 [#85] 강좌 등록 양식 페이지 추가
  src/main/webapp/elearn/course-registration-form.jsp
Labels: enhancement

#98 [#97] 강좌 등록 확인 페이지 추가
  src/main/java/org/chulgang/hrd/classroom/controller/GetTimePeriodsController.java
  src/main/java/org/chulgang/hrd/classroom/dto/GetClassroomResponse.java
  src/main/java/org/chulgang/hrd/course/controller/RegisterCourseController.java
  src/main/java/org/chulgang/hrd/course/domain/Course.java
  src/main/java/org/chulgang/hrd/course/dto/CreateCourseRequest.java
  src/main/java/org/chulgang/hrd/course/dto/GetSubjectResponse.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepository.java
  src/main/java/org/chulgang/hrd/course/model/repository/CourseRepositoryImpl.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseService.java
  src/main/java/org/chulgang/hrd/course/model/service/CourseServiceImpl.java
  src/main/java/org/chulgang/hrd/course/util/RequestConstant.java
  src/main/webapp/elearn/course-registration-confirm.jsp
Labels: enhancement

#99 feat(post): 게시판 수정 기능 추가
  src/main/java/org/chulgang/hrd/post/controller/UpdatePostController.java
  src/main/java/org/chulgang/hrd/post/model/repository/PostRepositoryImpl.java
  src/main/java/org/chulgang/hrd/post/model/service/PostService.java
  src/main/java/org/chulgang/hrd/post/model/service/PostServiceImpl.java
  src/main/java/org/chulgang/hrd/post/model/sql/PostSQL.java
  src/main/webapp/elearn/postInput.jsp
  src/main/webapp/elearn/postUpdate.jsp
Labels: enhancement

#102 [#101] 테스트 유틸 클래스 수정사항 추가
  src/test/java/org/chulgang/hrd/course/controller/GetCourseControllerTest.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestConstant.java
  src/test/java/org/chulgang/hrd/course/model/testutil/CourseTestObjectFactory.java
Labels: test
